In [2]:
import numpy as np

In [4]:
A = np.array([  [1, 2, 1],
                [3, 4, 7], 
                [5, 7, 8]])

B = np.array([  [5, 6, 9],
                [7, 8, 4],
                [2, -4, 7]])
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)

Matriz A:
[[1 2 1]
 [3 4 7]
 [5 7 8]]

Matriz B:
[[ 5  6  9]
 [ 7  8  4]
 [ 2 -4  7]]


In [5]:
# Soma de matriz
print('Soma:',A+B,'Subtracao:',A-B,sep='\n')

Soma:
[[ 6  8 10]
 [10 12 11]
 [ 7  3 15]]
Subtracao:
[[-4 -4 -8]
 [-4 -4  3]
 [ 3 11  1]]
